inp = input("Enter: ")
a = inp.isalpha()
b = inp.isalnum()
c = inp.isspace()
d = inp.isnumeric()
print("is an alphabet: ",a)
print("is an alphanumeric: ",b)
print("is a space: ",c)
print("is numeric: ",d)